# These are supported funding model platforms

github: [] # Add up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: "" # Add your Patreon username if applicable
open_collective: "" # Add your Open Collective username if applicable
ko_fi: "" # Add your Ko-fi username if applicable
tidelift: "" # Add your Tidelift package-name/platform-name if applicable
community_bridge: "" # Add your Community Bridge project-name if applicable
liberapay: "" # Add your Liberapay username if applicable
issuehunt: "" # Add your IssueHunt username if applicable
lfx_crowdfunding: "" # Add your LFX Crowdfunding project-name if applicable
polar: "" # Add your Polar username if applicable
buy_me_a_coffee: NeoDev99
custom: ["https://www.paypal.me/"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
